### ISSUE TITLE
Append not working in writing string to file

### ISSUE THREAD

**Issue by wingedrasengan927** [IncantaGames/unreal-bp-file-sdk#2] opened 2022-08-10 05:12 UTC
Hi, even if append is set to true, the file is being cleared every time. please look into this. attaching an example below

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/34920015/183820746-19b82bbd-db4e-4a66-ae54-0241d2da9f93.png">

<img width="665" alt="image" src="https://user-images.githubusercontent.com/34920015/183820795-4254e9b0-6b0a-4d95-b88b-6d8d9dba144d.png">

**Comment by mikeseese** [comment] 2022-08-10 05:30
Thanks for reporting this. Am I correct that you're running this on MacOS? What version of the plugin are you using? What version of Unreal are you using?

**Comment by mikeseese** [comment] 2022-08-10 05:40
I tested this just now on:
- Windows 11
- UE 5.0.3
- FileSDK 1.17

and it works as expected:

![image](https://user-images.githubusercontent.com/549323/183823766-045e8381-fb16-427c-9a9e-47a330f0400c.png)

![image](https://user-images.githubusercontent.com/549323/183823830-50192d88-eb2a-4754-9046-b07d43fac319.png)

So I believe that the issue may be related to a C++ compiler difference (Windows vs MacOS).

@wingedrasengan927 I believe have a potential fix; I'll look into it more tomorrow when I can test it on my Mac machine and let you know

**Comment by mikeseese** [comment] 2022-08-10 05:48
@wingedrasengan927 note that your while loop will never execute because `Condition` is unchecked

**Comment by mikeseese** [comment] 2022-08-10 06:57
Looks like I can reproduce the issue on MacOS with UE 5.0.3

**Comment by mikeseese** [comment] 2022-08-10 07:06
I have a fix; I'll push it to the marketplace sometime in the next week. I'll let you know when the update is available.

**Comment by wingedrasengan927** [comment] 2022-08-10 08:16
Thank You for the quick response.
I'm using Mac OS with UE version 4.27
Let me check in windows.

Again, appreciate the quick response and the fix.

**Comment by mikeseese** [comment] 2022-08-10 19:56
Thanks for the info! Looks like there's no need for further testing/info from you as I know the root cause now.

**Comment by mikeseese** [comment] 2022-08-11 16:36
This has been fixed in v2.0, released in the last few minutes. You may need to exit the epic games launcher and restart it for the update to show up.

**Closed as completed by mikeseese** 2022-08-11 16:36 UTC

**Comment by wingedrasengan927** [comment] 2022-08-15 08:47
It's working. Thanks a lot!
